version: '3.0'

services:
  db:
    build:
      context: ./services/postgress
    environment:
      POSTGRES_USER: odoo_admin
      POSTGRES_PASSWORD: odoo_admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /var/run/postgresql:/var/run/postgresql  # Monta o diretório do socket do PostgreSQL
    networks:
      - odoo_network

  odoo:
    build:
      context: ./services/odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odooaddons:/mnt/extra-addons
      - odoodata:/var/lib/odoo
      - odoologs:/var/log/odoo
      - /var/run/postgresql:/var/run/postgresql  # Monta o diretório do socket do PostgreSQL
    networks:
      - odoo_network

networks:
  odoo_network:
    driver: bridge

volumes:
  pgdata:
  odooaddons:
  odoodata:
  odoologs:
