version: '4'

services:
  db:
    image: postgres:latest
    build:
      context: ./services/postgress
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - odoo_network

  odoo:
    image: odoo:15
    build:
      context: ./services/odoo
    volumes:
      - odooaddons:/mnt/extra-addons
      - odoodata:/var/lib/odoo
      - odoologs:/var/log/odoo
    ports:
      - "8069:8069"
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=admin
      - PGPASSWORD=db_odoo
    networks:
      - odoo_network

networks:
  odoo_network:
    driver: bridge

volumes:
  pgdata:
  odooaddons:
  odoodata:
  odoologs:
